// packages/react/src/components/celtyui/charts/bar/barChart2/demo/index.tsx
import BarChart from 'src/components/celtyui/charts/bar/barChart2'
import '../../barChart1/demo/index.scss'

export default function BarChart2Demo() {
  const data: [number, string][] = new Array(7).fill('').map((s, i) => {
    return [Math.floor(Math.random() * 100), `${2018 + i}`]
  })

  return (
    <div className="bar-chart">
      <BarChart data={data} yName="单位/件" />
    </div>
  )
}

// packages/vue/src/components/celtyui/charts/bar/barChart5/demo/index.vue
<template>
  <div class="bar-chart">
    <BarChart :data="data" y-name="单位/件" />
  </div>
</template>

<script setup lang="ts">
import BarChart from 'src/components/celtyui/charts/bar/barChart5/index.vue'

const data: [string, number][] = new Array(7).fill('').map((s, i) => {
  return [`${2018 + i}`, Math.floor(Math.random() * 100)]
})
</script>

<style scoped lang="scss">
.bar-chart {
  width: 450px;
  height: 260px;
  background-color: #062040;
}
</style>
