// packages/vue/src/components/celtyui/charts/bar/barChart5/demo/index.vue
<template>
  <div class="bar-chart">
    <BarChart :data="data" y-name="单位/件" />
  </div>
</template>

<script setup lang="ts">
import BarChart from 'src/components/celtyui/charts/bar/barChart5/index.vue'

const data: [string, number][] = new Array(7).fill('').map((s, i) => {
  return [`${2018 + i}`, Math.floor(Math.random() * 100)]
})
</script>

<style scoped lang="scss">
.bar-chart {
  width: 450px;
  height: 260px;
  background-color: #062040;
}
</style>

// packages/react/src/components/celtyui/charts/bar/barChart3/demo/index.tsx
import BarChart from 'src/components/celtyui/charts/bar/barChart3'
import '../../barChart1/demo/index.scss'

export default function BarChart3Demo() {
  const data: Array<{
    name: string
    value: [any, number][]
  }> = ['A', 'B'].map(d => {
    return {
      name: d,
      value: new Array(7).fill('').map((s, i) => {
        return [`${2018 + i}`, Math.floor(Math.random() * 1000)]
      })
    }
  })

  return (
    <div className="bar-chart">
      <BarChart data={data} yName="单位/件" />
    </div>
  )
}
