// packages/react/src/components/celtyui/value/valueShow2/index.tsx
import AniNumber from '../aniNumber'
import './index.scss'

interface ValueShow2Props {
  data: {
    value: number
    label: string
    unit?: string
    icon?: string
  }
}

export default function ValueShow2(props: ValueShow2Props) {
  return (
    <div className="value-show2">
      <div className="val">
        <img src={props.data.icon} alt="" />
        <div className="num">
          <AniNumber value={props.data.value} />
          <span className="unit">{props.data.unit}</span>
        </div>
      </div>
      <div className="value-show2-label">{props.data.label}</div>
    </div>
  )
}

// src/components/vtscadd/value/valueShow2/index.vue
<template>
  <div class="value-show2">
    <div class="val">
      <img :src="props.data.icon" alt="" />
      <div class="num">
        <MAniNumber :value="props.data.value ?? 0" />
        {{ props.data.unit }}
      </div>
    </div>
    <div class="label">{{ props.data.label }}</div>
  </div>
</template>

<script setup lang="ts">
import { MAniNumber } from '@mo-yu/vue'

const props = defineProps<{
  data: {
    value: number
    label: string
    unit?: string
    icon?: string
  }
}>()
</script>

<style scoped lang="scss">
.value-show2 {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  .val {
    display: flex;
    align-items: flex-end;
    justify-content: center;
    img {
      width: 40px;
      height: 40px;
    }
    .num {
      font-size: 20px;
      color: #ffee00;
    }
  }
  .label {
    font-size: 16px;
    color: #ffffff;
  }
}
</style>
