// src/views/vtscadd/value/valueShow2/index.vue
<template>
  <ValueShow :data="data" />
</template>

<script setup lang="ts">
import ValueShow from 'src/components/vtscadd/value/valueShow2/index.vue'
import icon from 'src/assets/images/vue.svg'

const data = {
  label: '下次一定',
  value: 999,
  unit: '次',
  icon
}
</script>

<style scoped lang="scss"></style>

// packages/react/src/components/celtyui/value/valueShow2/index.tsx
import AniNumber from '../aniNumber'
import './index.scss'

interface ValueShow2Props {
  data: {
    value: number
    label: string
    unit?: string
    icon?: string
  }
}

export default function ValueShow2(props: ValueShow2Props) {
  return (
    <div className="value-show2">
      <div className="val">
        <img src={props.data.icon} alt="" />
        <div className="num">
          <AniNumber value={props.data.value} />
          <span className="unit">{props.data.unit}</span>
        </div>
      </div>
      <div className="value-show2-label">{props.data.label}</div>
    </div>
  )
}
