// packages/react/src/components/celtyui/charts/bar/barChart3/demo/index.tsx
import BarChart from 'src/components/celtyui/charts/bar/barChart3'
import '../../barChart1/demo/index.scss'

export default function BarChart3Demo() {
  const data: Array<{
    name: string
    value: [any, number][]
  }> = ['A', 'B'].map(d => {
    return {
      name: d,
      value: new Array(7).fill('').map((s, i) => {
        return [`${2018 + i}`, Math.floor(Math.random() * 1000)]
      })
    }
  })

  return (
    <div className="bar-chart">
      <BarChart data={data} yName="单位/件" />
    </div>
  )
}

// src/components/vtscadd/charts/bar/barChart3/demo/index.vue
<template>
  <div class="bar-chart">
    <BarChart :data="data" y-name="单位：个" />
  </div>
</template>

<script setup lang="ts">
import BarChart from 'src/components/vtscadd/charts/bar/barChart3/index.vue'

const data: Array<{
  name: string
  value: [any, number][]
}> = ['A', 'B'].map(d => {
  return {
    name: d,
    value: new Array(7).fill('').map((s, i) => {
      return [`${2018 + i}`, Math.floor(Math.random() * 1000)]
    })
  }
})
</script>

<style scoped lang="scss">
.bar-chart {
  width: 450px;
  height: 260px;
  background-color: #062040;
}
</style>
