// packages/react/src/components/celtyui/charts/line/lineSymbol/demo/index.tsx
import LineSymbol from 'src/components/celtyui/charts/line/lineSymbol'
import './index.scss'

export default function LineSymbolDemo() {
  const data: [string, number][] = new Array(7).fill('').map((s, i) => {
    return [`${2018 + i}`, Math.floor(Math.random() * 600)]
  })

  return (
    <div className="lines">
      <div className="line-chart">
        <LineSymbol data={data} symbol={0} yName="单位/个" />
      </div>
      <div className="line-chart">
        <LineSymbol data={data} symbol={1} yName="单位/个" />
      </div>
      <div className="line-chart">
        <LineSymbol data={data} symbol={2} yName="单位/个" />
      </div>
      <div className="line-chart">
        <LineSymbol data={data} symbol={3} yName="单位/个" />
      </div>
    </div>
  )
}

// src/components/celtyui/charts/line/lineChart2/demo/index.vue
<template>
  <div class="line-chart">
    <LineChart :data="data" y-name="单位/个" />
  </div>
</template>

<script setup lang="ts">
import LineChart from 'src/components/celtyui/charts/line/lineChart2/index.vue'

const data: Array<{
  name: string
  value: [any, number][]
}> = ['A', 'B', 'C'].map(d => {
  return {
    name: d,
    value: new Array(7).fill('').map((s, i) => {
      return [`${2018 + i}`, Math.floor(Math.random() * 100)]
    })
  }
})
</script>

<style scoped lang="scss">
.line-chart {
  width: 450px;
  height: 380px;
  background-color: #062040;
}
</style>
