// packages/react/src/views/portal/demoItem/DemoItem.tsx
import {
  lazy,
  Suspense,
  useRef,
  useEffect,
  useState,
  CSSProperties,
  LazyExoticComponent
} from 'react'
import { message } from 'antd'
import { useAppSelector } from 'src/store/hooks'
import { getDemos } from 'src/components/celtyui/demoAble'
import WordHighlight from 'src/components/celtyui/show/wordHighlight'
import { IDemoInfo } from 'root/utils/demos'
import './demoItem.scss'

interface DemoProps {
  demo: IDemoInfo
}

export default function DemoItem(props: DemoProps) {
  const [messageApi, contextHolder] = message.useMessage()
  const filterText = useAppSelector(state => state.menu.filterText)
  const key = `${props.demo.path}/demo/index.tsx`
  const [style, setStyle] = useState<CSSProperties>({})
  const [demo, setDemo] = useState<any>(null)
  const [DynamicComponent, setDynamicComponent] =
    useState<LazyExoticComponent<React.ComponentType<any>>>()
  const demoItem = useRef<any>(null)

  useEffect(() => {
    const observer = new MutationObserver(mutationsList => {
      for (const mutation of mutationsList) {
        if (mutation.type === 'childList' && mutation.addedNodes.length > 0) {
          const addedNode = mutation.addedNodes[0]
          if (addedNode.nodeType === Node.ELEMENT_NODE) {
            setDemo(addedNode)
            observer.disconnect()
          }
        }
      }
    })
    observer.observe(demoItem.current, { childList: true, subtree: true })

    return () => {
      observer.disconnect()
    }
  }, [])

  useEffect(() => {
    setDynamicComponent(lazy(getDemos()[key]))
  }, [key])

  useEffect(() => {
    if (demoItem.current && demo) {
      const { width: w1, height: h1 } = demo.getBoundingClientRect()
      const { width: w2, height: h2 } = demoItem.current.getBoundingClientRect()
      const scale = Math.min(w2 / w1, h2 / h1)
      if (scale < 1) {
        setStyle({
          transform: `scale(${scale})`
        })
      }
    }
  }, [demoItem.current, demo])

  function handleCopy(name: string) {
    navigator.clipboard
      .writeText(name)
      .then(() => {
        messageApi.success(`“${name}” 已复制到剪贴板！`)
      })
      .catch(err => {
        console.error('无法复制文本：', err)
      })
  }

  function toDemo(path: string) {
    window.open(`${window.location.origin}/#/demo?dir=${path}`, '_blank')
  }

  return (
    <>
      {contextHolder}
      <div className="demo-item">
        <div
          className="content"
          onClick={() => {
            toDemo(props.demo.path)
          }}>
          <div ref={demoItem} className="demo-content">
            <div style={style} className="demo">
              <Suspense fallback={<div>Loading...</div>}>
                {DynamicComponent ? <DynamicComponent /> : <></>}
              </Suspense>
            </div>
          </div>
        </div>
        <div
          className="label"
          onClick={() => {
            handleCopy(props.demo.name)
          }}>
          <i className="iconfont icon-fuzhi" />
          <WordHighlight text={props.demo.name} keywords={filterText} />
        </div>
      </div>
    </>
  )
}

// src/views/portal/demoItem/DemoItem.vue
<template>
  <div class="demo-item">
    <div class="content" @click="toDemo(props.demo.path)">
      <div ref="demoItem" class="demo-wrap">
        <div :style="style" class="demo">
          <Component :is="comp" ref="demoRef" />
        </div>
      </div>
    </div>
    <div class="label" @click="handleCopy(props.demo.name)">
      <i class="iconfont icon-fuzhi" />
      <MHighlight :text="props.demo.name" :word="store.filterText" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, markRaw, StyleValue, watchEffect } from 'vue'
import { useMessage } from 'naive-ui'
import { MHighlight } from '@mo-yu/vue'
import { IDemoInfo, useMenuStore } from '../menu/useMenu'
import { getDemos } from 'src/components/celtyui/demoAble'

const props = defineProps<{
  demo: IDemoInfo
}>()
const store = useMenuStore()
const message = useMessage()
const comp = ref<any>(null)
const style = ref<StyleValue>()
const demoItem = ref<any>(null)
const demoRef = ref<any>(null)

onMounted(() => {
  const key = `${props.demo.path}/demo/index.vue`
  getDemos()
    [key]?.()
    .then(c => {
      comp.value = markRaw(c?.default)
    })
    .catch(err => {
      console.error(err)
    })
})

watchEffect(() => {
  if (demoItem.value && demoRef.value?.$el) {
    const { width: w1, height: h1 } = demoRef.value.$el.getBoundingClientRect()
    const { width: w2, height: h2 } = demoItem.value.getBoundingClientRect()
    const scale = Math.min(w2 / w1, h2 / h1)
    if (scale < 1) {
      style.value = {
        transform: `scale(${scale})`
      }
    }
  }
})

function handleCopy(name: string) {
  navigator.clipboard
    .writeText(name)
    .then(() => {
      message.success(`“${name}” 已复制到剪贴板！`)
    })
    .catch(err => {
      console.error('无法复制文本：', err)
    })
}

function toDemo(path: string) {
  window.open(`${window.location.origin}/#/demo?dir=${path}`, '_blank')
}
</script>

<style scoped lang="scss">
.demo-item {
  width: calc(20% - 16px);
  height: 250px;
  position: relative;
  margin: 8px;
  border: 1px solid #dcdcdc;
  box-shadow: 4px 4px 4px 2px rgba(34, 47, 69, 0.24);
  border-radius: 4px;
  border: 1px solid #ccc;
  .content {
    width: 100%;
    height: calc(100% - 32px);
    padding: 6px;
    cursor: pointer;
    overflow: hidden;
    .demo-wrap {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      .demo {
        flex-shrink: 0;
        pointer-events: none;
      }
    }
  }
  .label {
    width: 100%;
    height: 32px;
    cursor: copy;
    text-align: center;
    line-height: 32px;
    color: white;
    font-size: 14px;
    border-radius: 0 0 4px 4px;
    background-color: rgba(0, 0, 0, 0.7);
    @include vars.textOver();
    i {
      margin-right: 4px;
    }
  }
}
</style>
