// src/components/vtscadd/charts/commonChart/index.vue
<template>
  <div :id="chartId" class="common-chart"></div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, reactive, watch } from 'vue'
import { EChartsOption } from 'echarts'
import { guid } from '@mo-yu/core'
import useCharts, { ChartsOption } from './useChart'

const props = defineProps<{
  option?: EChartsOption
}>()
const chartOption: ChartsOption = reactive({ chartId: '' })
const { clearChart } = useCharts(chartOption)
const chartId = guid()

onMounted(() => {
  chartOption.chartId = chartId
  chartOption.option = props.option
})

onBeforeUnmount(() => {
  clearChart()
})

watch(
  () => props.option,
  next => {
    chartOption.option = next
  }
)
</script>

<style scoped lang="scss">
.common-chart {
  width: 100%;
  height: 100%;
}
</style>

// packages/react/src/components/celtyui/charts/commonChart/index.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { EChartsOption } from 'echarts'
import useCharts, { ChartsOption } from './useChart'
import { genUuid } from '../../util/genUuid'

interface CommonChartProps {
  option?: EChartsOption
}

export default function CommonChart(props: CommonChartProps) {
  const id = useRef(genUuid())
  const [option, setOption] = useState<ChartsOption>({ chartId: '' })
  const { chartId, clearChart } = useCharts(option)
  const computedOption = useMemo(() => {
    return {
      chartId: id.current,
      option: props.option
    }
  }, [props.option])

  useEffect(() => {
    setOption({ chartId: id.current, option: props.option })
    return () => {
      clearChart()
    }
  }, [])

  useEffect(() => {
    if (chartId) {
      setOption(computedOption)
    }
  }, [computedOption])

  return <div id={id.current} style={{ width: '100%', height: '100%' }}></div>
}
